name: 'test-2'

on:
  push:
    paths:
      - 'test-2/*'
      - '!test-2/*/*'
      
jobs:
  call-terraform-workflow:
    uses: rafavallina/tf-os-sample/.github/workflows/terraform.yml@main
    with:
      role_arn: 'arn:aws:iam::914735543492:role/ExampleGithubRole'
      environment: 'test-2'
      aws_region: 'us-east-1'
