name: 'test-2'

on:
  push:
    paths:
      - 'test-2/*'
      - '!test-2/*/*'
      
jobs:
  call-terraform-workflow:
    uses: rafavallina/tf-os-sample/.github/workflows/terraform.yml@main
    with:
      role_arn: 'arn:aws:iam::617296401743:role/TerraformGitHubActionsRole'
      environment: 'test-2'
