name: 'tf-test'

on:
  push:
    paths:
      - 'tf-test/*'
      
jobs:
  call-terraform-workflow:
    uses: rafavallina/tf-os-sample/.github/workflows/terraform.yml@main
    with:
      role_arn: 'arn:aws:iam::914735543492:role/ExampleGithubRole'
      environment: 'tf-test'
      aws_region: 'us-east-1'
